server:
  port: 8989
spring:
  application:
    name: love-music
  profiles:
    active: dev # ??????
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${love-music.mysql.host}:${love-music.mysql.port}/${love-music.mysql.db}
      username: ${love-music.mysql.username}
      password: ${love-music.mysql.password}
  redis:
    host: ${love-music.redis.host}
    database: ${love-music.redis.database}
    port: ${love-music.redis.port}
    password: ${love-music.redis.password}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: ${love-music.jwt.secret}