server:
  port: 8989
spring:
  application:
    name: love-music
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false # close spring devtools restart
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${love-music.mysql.host}:${love-music.mysql.port}/${love-music.mysql.db}?serverTimezone=UTC
      username: ${love-music.mysql.username}
      password: ${love-music.mysql.password}
  redis:
    host: ${love-music.redis.host}
    database: ${love-music.redis.database}
    port: ${love-music.redis.port}
    password: ${love-music.redis.password}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-prefix: money
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/v1/*.xml

# logging level print
logging:
  level:
    root: info
    com.devin.love.music.mapper*: debug
    org.springframework.jdbc.core: debug
    com.alibaba.druid: debug
  file:
    name: ./logs/love-music.log

jwt:
  secret: ${love-music.jwt.secret}